BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/qca_cld3_wlan.ko
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/wlan_firmware_service.ko
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/cnss_nl.ko
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/cnss_prealloc.ko
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/cnss_utils.ko
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/icnss2.ko

WIFI_DRIVER_STATE_CTRL_PARAM := "/dev/wlan"
WIFI_DRIVER_STATE_ON := "ON"
WIFI_DRIVER_STATE_OFF := "OFF"
